name: actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v4
      - name: Setup
        run: make setup
      - name: Test
        run: make test
      - name: Lint
        run: make lint
